### PR TITLE
libffi: use an HTTPS mirror

### PR DESCRIPTION
**Pull request by chouquette**
We seem to sometimes have errors when fetching from FTP: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/536079168

### CODE REVIEW

**Review by alopezz — APPROVED** [review]
I thought we cached all of these, though.

**Comment by chouquette** [comment]
> I thought we cached all of these, though.

We do, but as we noticed an issue with the license caching we also started a pipeline with the entire S3 cache disabled, which failed

**Pull request merged**
