### PR TITLE
Fix cacerts checksum missmatch

### PR DESCRIPTION
**Pull request by albertvaka**
- Update checksum
- Pin a specific version, so another update doesn't break the builds

### CODE REVIEW

**Comment by olivielpeau** [comment]
@albertvaka always pulling the latest version was a feature, not a bug. It forced us to always ship the latest CA certs at the time of the build with the Agent.

Let's discuss if it's still relevant to do this though

**Comment by albertvaka** [comment]
@olivielpeau I see the benefits, but on the other hand it doesn't help with build reproducibility.

I can revert it to use latest and just update the checksum, no strong opinion on it.

**Comment by derekwbrown** [comment]
I think we need to go back to using latest... otherwise starting with the next change we'll always be using an out of date cert and we'll never know.  Better to have a build breakage ~ once a month than have an out of date root cert.

**Comment by albertvaka** [comment]
@derekwbrown https://github.com/DataDog/omnibus-software/pull/323

**Pull request merged**
