### PR TITLE
Bump kafka-python to 1.3.1

### PR DESCRIPTION
**Pull request by jeffwidman**
There's a number of bug fixes and issues since the 1.2.5 release.

Details in https://github.com/DataDog/dd-agent/pull/2863

### CODE REVIEW

**Comment by jeffwidman** [comment]
@olivielpeau anything else you need from me on this?

**Comment by jeffwidman** [comment]
Bump

**Comment by jeffwidman** [comment]
Actually should be merged with https://github.com/DataDog/dd-agent/pull/3097 as https://github.com/DataDog/dd-agent/pull/#2863 had unfixable merge conflicts.

**Comment by olivielpeau** [comment]
Just merged DataDog/dd-agent#3097, merging this one as well, thanks @jeffwidman!

**Pull request merged**
