### PR TITLE
[gohai][windows] Pass version to go build command

### PR DESCRIPTION
**Pull request by olivielpeau**
Related to https://github.com/DataDog/gohai/pull/19

### CODE REVIEW

**Comment by remh** [comment]
Why are we doing that just for Windows @olivielpeau ?

**Comment by remh** [comment]
I see it's done here: https://github.com/DataDog/omnibus-software/pull/28

Why not do both in one pass ?

**Comment by olivielpeau** [comment]
I've opened this separate PR against `etienne/windows` because the windows support is not merged into master yet.

**Comment by yannmh** [comment]
Looks good :+1:

**Pull request merged**
